### ISSUE TITLE
2023 Addons

### ISSUE THREAD

**Issue by MelSumner** [MelSumner/why-ember#42]
Skipped 2022 (oops!) but let's get a list together for 2023! 

Criteria for inclusion:

- any Ember addon that is not included in the default blueprint.
- can use in a current new Ember app

**Comments from the community with your favorite addon, and why, are welcome!**

**Comment by void-mAlex** [comment]
ember-a11y-testing - saves tons of manual testing time dealing with a11y
ember-intl - if you need any translations

**Comment by MichalBryxi** [comment]
- Whole [frontile.dev](https://frontile.dev/) family for anything forms / notifications / modals related.
- [ember-animated](https://github.com/ember-animation/ember-animated) - seems a bit unloved, but I adore the simplicity it brings to animations.
- [ember-web-app](https://zonkyio.github.io/ember-web-app/) - I really don't want to go to the nitty gritty of how this is supposed to work, just please set it up for me, thank you.
- [ember-responsive-images](https://github.com/simonihmig/ember-responsive-image) - Either you're using this addon or you're doing images wrong :)
- [ember-apply](https://github.com/NullVoxPopuli/ember-apply) - Le cheff-kiss for setting up things and not having to care.
- [ember-animate-css](https://github.com/sinankeskin/ember-animate-css) - I like animations, ok?

**Comment by MelSumner** [comment]
@MichalBryxi thanks for this list! I think I might need to try a few of these out!

**Comment by IgnaceMaes** [comment]
Not addons in the classic sense, but they had the biggest impact for me:
- [ember-template-imports](https://github.com/ember-template-imports/ember-template-imports): Template tag components 🥇 
- [glint](https://github.com/typed-ember/glint): Type checking for Glimmer templates.
- [prember](https://github.com/ef4/prember): Pre-render your Ember app to static pages so it can be deployed on a static web host.

Some "actual" addons, not yet mentioned:
- [@bagaar/ember-pagination](https://github.com/Bagaar/ember-pagination): A very solid addon which contains logic to build your own pagination component on.
- [ember-heroicons](https://github.com/tzellman/ember-heroicons): A quick and easy way to use Hero icons in an Ember app.

**Comment by MelSumner** [comment]
Other candidates from DMs:

- ember-changeset
- ember-concurrency
- ember-truth-helpers
- ember-simple-auth
